In [27]:
print("numpy is a module or library for scientific computing and it contains powerful n -dim array object and tools for integrating with c or c++ and in linear alegbra for fouriour transform and random number capabilities \n ")
print("it can be used as a multi-dim container for generic data. ")
print("numpy use contigouos memory concept and each element are store in same block size of memory.")

numpy is a module or library for scientific computing and it contains powerful n -dim array object and tools for integrating with c or c++ and in linear alegbra for fouriour transform and random number capabilities 
 
it can be used as a multi-dim container for generic data. 
numpy use contigous memory concept and each element are store in same block size of memory.


In [ ]:
import numpy as np
#pandas and numpy both are core structure to handle the data,and both are use for dealing with data 
#scipy deals for modelling data
print("numpy stands for numerical python,\n it is the package for mathematical computing.\n logical operations on arrays.\"data in the matrices form means rows and column")
#basic ndarray
print(" deals with multidimensional array,how to represent data ")
print("homogenous collection of data")
print("fast and efficient")
print("support for mathematical functions")


In [1]:
import numpy as np 
a1=np.array([1,2,3])
print("this is 1-dim array:::",a1)
a1[0]=10.3   #if we will assign float value then it will take round about value

print(a1) #numpy is mutable ,means once we create then we can easily change the value 
print('\n')


a2=np.array([(1,2,3),(4,5,6)])
print("this is a 2-dim array",a2)


arr3 = np.array((1, 3, 2))
print("Creating an array from tuple",arr3)


arr4=np.array((1,2,3),dtype=np.float64)
print(arr4)

this is 1-dim array::: [1 2 3]
[10  2  3]


this is a 2-dim array [[1 2 3]
 [4 5 6]]
Creating an array from tuple [1 3 2]
[1. 2. 3.]


In [3]:
#numpy attributes 
import numpy as np
a=np.array([(1,2,3),(3,4,5)])

print("dimensional of array is ",a.ndim)

a=np.array([(1,2,3),(3,4,5)])
print("shape of an array in the form of n*m means rows*column",a.shape)

print("total number of elements ",a.size)

print("type of an array ",a.dtype)

print("itemsize of each element in bytes ",a.itemsize)

print("the buffer containing the actual elements of the array",a.data)

print("tell the total element size in bytes 4(bytes)*6(element)*",a.nbytes)

dimensional array is  2
shape of an array in the form of n*m means rows*column (2, 3)
total number of elements  6
type of an array  int32
itemsize of each element in bytes  4
the buffer containing the actual elements of the array <memory at 0x000002BEC3D4FC18>
tell the total elemnt size in bytes 24


In [ ]:
#from numpy matrix to numpy array
np.array(np.mat('1 2;3 4;5 6'))

#type precedence :bool,int ,str,float 

# Type casting /type conversion

In [ ]:
a=np.array([1,2,3.0])
#type casting means just like in list we have homogenous data it will take as it is but in array any one of value is another type then it will change all other data type automatically 

#in this example a have float value if we will print this it will print float value all 
print(a)
print("\n")
#how to control this behaviour :we can explicitly defined data type 
print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=complex))
print(np.array([1234,4,5],dtype='U'))  #'U' STRING TYPE 
print(np.array([1234,2,3],dtype='<U2'))

print("*****example***********")
x=np.array([('ram',26,2300.0),('shivam',31,5000)],dtype=[('name','<U11'),('age','int32'),('salary','<f4')])
print("row1",x[0])
print("row2",x[1])


In [7]:
#why we use numpy 
import numpy as np 
import time
import sys
list1=range(1000)
print(sys.getsizeof(5)*len(list1))
nump1=np.arange(1000)
print(nump1.size*nump1.itemsize)
print("\n speed and convenient")
size=10000
l1=range(size)
l2=range(size)
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result=a1+a2
print("time taken by array",(time.time()-start)*1000)

28000
4000

 speed and convenient
0.0
time taken by array 0.0


In [15]:
#Python Program to Generate a Random Number
import random
values=random.random() 
print("each time it will generate random value betwen 0 and 1",values)#when a,b values is not specify then it will print random values between 0 to 1


values2=random.uniform(1,6) #uniform(a,b) is use to print floating point number
print("it will generate only 1 number  each time ",values2)

values3=random.randint(1,6)#randint is use to generate number in whole number 
print("randint will generate only 1 whole number",values3)


#choice method is use to pick only 1 random values from the list 
lis=["hello","hy","ajay","karan","jyoti","vaibhav"]
value=random.choice(lis)
print(value)




colors=["red","black","green"]
result=random.choices(colors,weights=[18,18,2],k=10)
print(result)

print("\n")
#deck of cards 
import random
deck=list(range(1,53))       
random.shuffle(deck)
print(deck)


print("****************************************")
hand=random.sample(deck,k=5)  #sample() will give in result as a unique value but choices will give repeteadly values 
print(hand)


print("\n20 samples drwan from a dice throw")
print(np.random.randint(1,7,20))


each time it will generate random value betwen 0 and 1 0.5746525412707331
it will generate only 1 number  each time  4.125783822185795
randint will generate only 1 whole number 5
hello
['red', 'red', 'red', 'red', 'red', 'black', 'black', 'red', 'red', 'green']


[1, 10, 41, 11, 17, 4, 14, 32, 31, 3, 29, 2, 36, 22, 12, 51, 47, 21, 7, 42, 16, 37, 30, 35, 6, 20, 13, 33, 27, 19, 28, 50, 40, 49, 52, 38, 5, 43, 24, 25, 39, 34, 15, 23, 44, 26, 8, 46, 48, 9, 18, 45]
****************************************
[3, 29, 50, 16, 43]

20 samples drwan from a dice throw
[1 6 5 4 3 1 1 2 2 6 1 4 6 5 3 1 2 4 1 1]


# numpy important function 

In [5]:
#array  creation routines 
#np.zeros(shape,order='C'/'F',dtype=None):creates an array full of zeros   C-COLUMN,F -ROW/shhape is just a tuple 
np.zeros( (3,4)) 
print("***************")

#np.ones(shape,order='C'/'F',dtype=None) creates an array full of ones 
np.ones( (2,3,4),dtype=np.int16)
print("******************************")


#np.empty(shape,dtype,order):creates an array whose initial content is random 
np.empty((2,3))    #uninitialized output may vary 


#custom type
x=np.zeros((2,2),dtype=[('x','i4'),('y','i4')])
print(x)




#np.eye(shape,k=0,dtype,order) :create an identity matrix with the shape bydefault float type 
np.eye(6)   #sqaure matrix :means rows and columns are same 
np.eye(6,k=1)

print("\n\n")
arr=np.array([[1,2,3],[5,6,7]])
print(arr)
print("\n")
print(np.diag(arr,k=1))    #diagonal of this array

***************
******************************
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]



[[1 2 3]
 [5 6 7]]


[2 7]


In [42]:
#super simple module to create basic random data for tutorials
import random
f_name=["john","jane","corey","travis","davie","kurt","neil","sam","steve","tom","james","karan","vaibhav","arjun","taniya","ashok","viyan","abhinav","khusi","anant","komal","naseeb","lakshay","prachi","mayanak","amit","sumit","dharambir","ajay","akash"]
last_name=["smith","katiyar","jenkins","robinson","gulia","katiyar","yadav","daharan","davis","starut","jacobs","wright","doe"]
street_names=["main","high","pearl","oak","pine","cedar","elm","washington"]
fake_cities=["metropolis","eeric","king","sunnydale","bedrock","southpark","atlantiics"]
states=["haryana","gujarat","himachalpa s = 'hello world'
rdesh","andharpardesh","assam","kerala","guhawati","bihar"]
for num in range(3):
    first=random.choice(f_name)
    last=random.choice(last_name)
    #phone=f"{random.randint(100,999)}-555-{random.randint(1000,9999)}"
    street_num=random.randint(100,999)
    street=random.choice(street_names)
    city=random.choice(fake_cities)
    state=random.choice(states)
    zip_code=random.randint(10000,99999)
    address=f"{street_num} {street} St.,{city} {state} {zip_code}"
    email=first.lower()+last.lower()+ "@bogusemail.com"
    print(f"{first} {last} \n{address}\n{email}\n")


steve gulia 
602 main St.,king haryana 13809
stevegulia@bogusemail.com

komal gulia 
406 high St.,eeric bihar 82139
komalgulia@bogusemail.com

ashok katiyar 
175 washington St.,atlantiics haryana 14944
ashokkatiyar@bogusemail.com



In [13]:
#numpy array from existing data 


#np.asarray(a,dtype,order=None)  :it will create array but it has less parameter 
import numpy as np
x=[1,2,3]
ar1=np.asarray(x)
print(ar1)
#np.frombuffer(buffer,dtype,count=-1,offset=0)  :this function interprets a buffer as 1-dim array,default=float,count=-1 no of items to be read,by default(-1),offset:starting position to read from (by deafult 0)
s='Hello world'

#a=np.frombuffer(s,dtype='S1')



#np.fromiter(iterable,dtype,count=-1)::it builds an ndarray object from an iterable object.
lis=range(5)
it=iter(lis)
x=np.fromiter(it,dtype=float)
x

[1 2 3]


array([0., 1., 2., 3., 4.])

# array from numerical ranges     range vs arange vs linspace

In [21]:
import numpy as np
a=list(range(10))
a     #it will create a list of the values what we want    
#create only range  and does not accept float arguments 
print(list(range(11,0,-1)))






#np.logspace(start,stop,num,endpoint,base,dtype)  base usually 10 
a=np.logspace(1.0,2.0,num=10)
print(a)
b=np.logspace(1,10,num=10,base=2)

print("\n")
print(b)


range example range(0, 10, 2)
arange example [0 1 2 3 4 5 6 7 8 9]
(array([ 0.        ,  1.16666667,  2.33333333,  3.5       ,  4.66666667,
        5.83333333,  7.        ,  8.16666667,  9.33333333, 10.5       ]), 1.1666666666666667)
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [ ]:
#arange :np.arange(start,stop,step)   #it will give matrix and range will give output in the list format 
#to create a sequence of numbers ,Numpy provides a function analogous to range that returns that arrays 
import  numpy as np
a=np.arange(10,100,5.4)   #not include stop element 
print(a)                  #accept float argument 
#when we use floating point argumnets ,generally it is impossible to predict no. of elements obtained thats why we use linsapce 

In [6]:
#np.linspace(start,stop,number,endpoint=Flase/True,restep=True,False,dtype)
print("linspace return  values within given interval")
b=np.linspace(1,100,10,endpoint=False,retstep=True)
print(b)
#bydefaultendpoint=True it include stop element butvendpoint=False(not include last element) 
#when retstep=True   tell how much difference between each value 


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from math import pi,cos,sin
x=np.linspace(0,2*pi,100)
y=np.sin(x)
plt.plot(y)
plt.show()

linspace return  values within given interval
(array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1]), 9.9)


<Figure size 640x480 with 1 Axes>

In [ ]:
print(np.arange(10000))   #it will print [0,1,2.......9999]  it's try to save memory
#if size of array is very large ,Numpy automatically tries limit the printing on screen.we can override this behaviour by setting print options
print(np.set_printoptions(threshold=1000))
print(np.arange(1000))

# BROADCASTING

In [ ]:
#Broadcasting:in python we perform operation element wise now suppose we have 2 array of different shape 1 is small and another is large shape 
#means operation on non -similiar shapes array done by broad casting 
print("rule 1:::size of each dimesnion is same,size of 1 array should be 1 dim")
a=np.arange(12).reshape(3,4)
print(a)
b=np.arange(3).reshape(3,1)

print(b)
a+b

# iterate numpy array using nditer

In [11]:
#iterate numpy array using nditer
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)



for row in a: #simple for loop does not print all the elements one by one properly
    print(row)
#above we are using for loop for doing iteration , now we can do iteration easily without for loop in numpy 

print("\n")
#same thing using nditer ():it provides more sophiticsted way to iterate 
for x in np.nditer(a,order='C'):  # C-row ,F-COLUMN 
    print(x)
    
    
for x in np.nditer(a,order='F'):
    print(x,end=",")
print("\n")
    
    
#looping over 2-dim (2d) array 
attendance=np.array([ [35,32],[37,28],[39,34],[33,36],[36,30]])
print("original array",attendance)

for a in np.nditer(attendance):
    print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


0
1
2
3
4
5
6
7
8
9
10
11
0,4,8,1,5,9,2,6,10,3,7,11,

original array [[35 32]
 [37 28]
 [39 34]
 [33 36]
 [36 30]]
35
32
37
28
39
34
33
36
36
30


# ARRAY MANIPULATION/changing shape 

In [14]:
#reshape method:give a new shape to an array without changing its data 
import numpy as np
a=np.arange(10)
print(np.arange(10).reshape(2,5))  #2rows*5column
print(np.arange(24).reshape(2,3,4))   #3 d array 

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
#np.flat():this function returns a 1-d iterator over the array  or it returns element corresponding to index in flatten array 
ar1=np.arange(8).reshape(2,4)
print(ar1.flat[7])

7


In [ ]:
#ravel(order='F'):IT returns contiguous flattened array(1d array)
import numpy as np
a=np.arange(15).reshape(3,5)
print("original array\n",a)

#output comes like [0,1,2,3....]
print(a.ravel())
print(a.reshape(-1))     #a.ravel() is equivalent to a.rehshape(-1)


In [ ]:
#a.flatten(order='C','F'):IT returns a copy of an array collapsed into 1 dim 
a=np.arange(12).reshape(3,4)
a.flatten()     #order='C' by default 
a.flatten(order='F')


#difference between ravel and flatten 
print("ravel:return only reference/view of an original array,we will change in copy ,original array will also change,ravel is faster than flatten,and ravel is library -level function")

print("return a copy, original array will not change when we change in the copy array")
print("flatten is slower,it is a method of an ndarry object")

In [13]:
import numpy as np
#np.transpose(arr,axes)
a=np.arange(15).reshape(3,5)
print(a)


print("original array shape",a.shape)
print(np.transpose(a))  
print(a.T)  #a.T WILL work as np.transpose(a)
print("after transpose an array",a.T.shape)
print("*****************")

#np.rollaxis(arr,axis,start)
print(np.rollaxis(a,0,2))

#print("row become column and column become row",np.transpose(a,(2,1,0)))
print("by default reverse the order but you can specify the order",a.shape)


#transmoveaxis
a=np.arange(24).reshape(2,3,4)
print("shape of original array",a.shape)
b=np.rollaxis(a,1,0)
print(b)
print("shape after move axis",b.shape)



#swap axis:
c=np.swapaxes(a,2,1)
print(c)
print("after swaping the axes",c.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
original array shape (3, 5)
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
after transpose an array (5, 3)
*****************
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
by default reverse the order but you can specify the order (3, 5)
shape of original array (2, 3, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
shape after move axis (3, 2, 4)
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
after swaping the axes (2, 4, 3)


# joining array 

In [18]:
#np.concatenate(a1,a2,axis=0/1) ::combine two or more arrays 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10,11,12],[13,14,15]])

print(a)
print(b)
print("\n")
print(np.concatenate((a,b),axis=1))


print("stack :: np.stack(array,axis=0/1)")
print(np.stack((a,b),axis=1))         #joins the sequence of arrays along a new axis
print("horizontal stack means ---- ")
print(np.hstack((a,b)))
print("vertical stack means ||||")
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]
stack :: np.stack(array,axis=0/1)
[[[ 1  2  3]
  [10 11 12]]

 [[ 4  5  6]
  [13 14 15]]]
horizontal stack means ---- 
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]
vertical stack means ||||
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


# argmax vs max

In [ ]:
#difference between argmax and max 
a=np.array([[9,10,100],[20,30,40]])
print(a)
print(a.max(axis=0))     #0-column          #a.max(axis=None, out=None, keepdims=False)

              #np.argmax(a, axis=None, out=None)
#argmax() :return the indices of the maximum values along an axis
print(np.argmax(a,axis=1))   #1 row 

#**********another example **********
a=np.arange(6).reshape(2,3)+10
print(a)
print("another example",np.argmax(a,axis=0))


#when value is repaetedly then it will give 1st occurence index 
a=np.array([2,3,4,5,2])
print(np.argmax(a))

# string function 

In [58]:
#concatination of character using numpy 
print("concatination")
print(np.char.add(['hello','hi'],['amit','anant']))
print(np.char.center("hello",20,fillchar="*"))
print(np.char.capitalize(['hello','world']))
print(np.char.capitalize(['hELLO']))
print(np.char.lower(['AMIT','GULIA']))
print(np.char.splitlines("hello \n how are you"))

concatination
['helloamit' 'hianant']
*******hello********
['Hello' 'World']
['Hello']
['amit' 'gulia']
['hello ', ' how are you']


# numpy mathematical functions  

In [19]:
#numpy mathematical functions 
import numpy as np
import math 
a=np.array([0,30,45,60,90])
sin_value=np.sin(a*np.pi/180)  #firstly convert into radian 
print(sin_value)

#now convert into  sin inverse of angles 
sin_inv=np.arcsin(sin_value)
print("sin inverse values",sin_inv)
print("check result by converting to degrees",np.degrees(sin_inv))

print("******************************")
#np.around(,a,decimals=1,-1)
b=np.array([1.00,5.55,0.567,25.532])
print(np.around(a,decimals=-1))   #decimals default is 0 but if negative the integer is rounded to position to the left of the decimal point 

print("*******************************************************")


print(np.round(sin_inv,2))  #round(array,decimal=2) #upo how many point you want to print
print(np.floor([-1.23,-2.345])) #np.floor(value) largest value print from he given value 
print(np.ceil([-1.23,-2.345]))  #np.ceil(value) print lowest value from the given value

[0.         0.5        0.70710678 0.8660254  1.        ]
sin inverse values [0.         0.52359878 0.78539816 1.04719755 1.57079633]
check result by converting to degrees [ 0. 30. 45. 60. 90.]
******************************
[ 0 30 40 60 90]
*******************************************************
[0.   0.52 0.79 1.05 1.57]
[-2. -3.]
[-1. -2.]


In [45]:
#numpy array indexing and slicing  in 1 dim array 
import numpy as np
a=np.arange(5)**2
print(a[2])
print("access element using index :::")
print(a[0:2])
print('\n')
print(a[-4:-1])
b=np.arange(10,1,-2)   #with negative step 
print(b)
print(b[2])
c=np.arange(0,20)
print(c)
print(c[-8:17:1])

#2d array 
a=np.arange(6).reshape(2,3)
print("2 d array\n",a)
#iterating #cube of a number 
import numpy as np
a=np.arange(1,7)
for i in a:
    print(i**3,end=",")

4
access element using index :::
[0 1]


[1 4 9]
[10  8  6  4  2]
6
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16]
2 d array
 [[0 1 2]
 [3 4 5]]
1,8,27,64,125,216,

In [21]:
#access the elements/slicing:selecting the item from the array 
a2=np.array([ [1,2,3,4],[3,4,5,6]]) #2 rows 4 column 
print(a2[0,2])
print(a2[0:,3])  #acess from both the rows and column select 3 index
a3=np.array([ [1,2,3,4],[3,4,5,6],[7,8,9,10]])
print(a3[0:,3])
print(a3[0:2,3])

a=np.array([[1,2,3],[4,5,6,7],[100,200]])
#axis rows(axis=0,column=axis=1)
a3=np.array([ [1,2,3,4],[3,4,5,6],[7,8,9,10]])
print("max according to rows(axis=0)",np.amax(a3,axis=0))
print("min according to column",np.amin(a3,axis=1))
print("sum according to rows",a3.sum(axis=0))
print("sum according to column",a3.sum(axis=1))






3
[4 6]
[ 4  6 10]
[4 6]
max according to rows(axis=0) [ 7  8  9 10]
min according to column [1 3 7]
sum according to rows [11 14 17 20]
sum according to column [10 18 34]


In [ ]:
#transform of string into list
s="jyoti"
print(list(s))
case="hello, my ,name ,is ".split(",")
print(case)



#reverse of the string 
print("reverse ",s[-1::-1])



#list to string
lis=['s','t','o','p']
name_str="??".join(lis)  #join is use to convert list to string
print(name_str)


#WHAT IS NEGATIVE INDEX IN python :
print("extracting the element from the backside called negative indexing")


#without traversing complete array tell the last element 
a=[1,2,3,4,5]
print(a[-1])



#difference between list and tuple
#synatx (2) list mutable and tuples immutable (3) list are slower and tuple is slower

#differnce between python 2 and python3
print("print is a function in python 3 but statemnt in python2,floating point in python3 (divide method),whereas in python 2 we get truncate value(divide time)")

In [16]:
#byteswap
import numpy as np 
a = np.array([12,34,56,78], dtype = np.int16) 
print ('Representation of data in memory in hexadecimal form:')  
print (hex,a)  
# byteswap() function swaps in place by passing True parameter 

print ('Applying byteswap() function:') 
print (a.byteswap(True))
print ('In hexadecimal form:') 
print (map(hex,a))
# We can see the bytes being swapped


Representation of data in memory in hexadecimal form:
<built-in function hex> [12 34 56 78]
Applying byteswap() function:
[ 3072  8704 14336 19968]
In hexadecimal form:


# sort vs argsort 

In [25]:
import numpy as np
a=np.array([ [3,7,0,2,5],[9,1,10,6,2]])
print(np.sort(a))
print('\n')
print(np.sort(a,axis=0))
print('\n')
print(np.sort(a,axis=1))


#argsort() is use to return the indices of an array according to sort 
print('\n after applying argsort()')
u=np.argsort(a)
print(u)

print("\n")
print(np.extract(u,a))
print('\n')


[[ 0  2  3  5  7]
 [ 1  2  6  9 10]]


[[ 3  1  0  2  2]
 [ 9  7 10  6  5]]


[[ 0  2  3  5  7]
 [ 1  2  6  9 10]]

 after applying argsort()
[[2 3 0 4 1]
 [1 4 3 0 2]]


[ 3  7  2  5  9  1 10  2]




In [34]:
#lexsort()
sur_names=('gulia','deswal','katiyar','malik','jadeja')
f_name=('amit','jyoti','karan','sonu','dilbar')

ind=np.lexsort((f_name,sur_names))
print("indices of an array",ind)
print([sur_names[i]+ " "+f_name[i] for i in ind])

indices of an array [1 0 4 2 3]
['deswal jyoti', 'gulia amit', 'jadeja dilbar', 'katiyar karan', 'malik sonu']


In [67]:
import numpy as np
a=np.array([40,10,50,60,0,1,2])
print(a.max())
print(a.min())
largest=a[0]
for i in range(0,len(a)):
    if largest==a[0]:
        print("largest number found")
    else:
        print("not found")

60
0
largest number found
largest number found
largest number found
largest number found
largest number found
largest number found
largest number found


In [74]:
import numpy as np

a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print(np.max(a,1))
print(np.amax(a,1))
print(np.ptp(a))

[7 8 9]
[7 8 9]
7


In [93]:

#2 d array indexing and slicing /iteration
b=np.array([[0,30,-1],[5,6,7]])
print(b)
print("***")
print(b[0:2,1])
#mathematical operation 
print("sum of rows ",b.sum(axis=0))
print("sum of columns",b.sum(axis=1))
print("standard deviation",b.std(axis=1))
print("sqaure root",np.sqrt(b))
print("sorting",np.sort(b,axis=1))
#boolean array indexing 
z=np.array([2,3,4,5,6,7,8])
print(z>4)  #it will give boolean value 
print(z[z>4]) #it will give value 

[1 2 3]
[ 1  2 20]
[ 1  2 10]


In [ ]:
#np.flip(m,axis=0):reverse the elements in an array along with axes 
a=np.arange(24).reshape(6,4)
print(a)
print(np.flip(a,axis=0)) 


In [ ]:
#statistical function 
a=np.array([2,3,4,50,60,100])
print("mimimum value",np.amin(a))
print("maximum value",np.amax(a))
#DIFFERENCE BEWTEEN amin and a.min(doe not work on order='C'/'F')
print("maximum-minimum",np.ptp(a))
print(np.percentile(a,q=50))
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(pow(a,b))
print(np.mod(b,a))


In [ ]:
import numpy as np
print(np.__version__)
ar1=np.array([1,2,3,4],dtype=bool)
print("this is 1d  and boolean array",ar1)
#How to extract items that satisfy a given condition from 1D array?
ar2=np.array([0,1,2,3,4,5,6,7,8,9])
con=ar2%2==1
print(np.extract(con,ar2))
#How to replace items that satisfy a condition with another value in numpy array
ar2[ar2%2==1]=-1
print(ar2)
#How to replace items that satisfy a condition without affecting the original array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
res=arr.copy()
res[res%2==1]=-1
print("original array is same but cahnge only in new array",res)
#How to reshape an array?
ar=np.arange(10).reshape(2,5)
print("reshape of an array",ar)
#How to generate custom sequences in numpy without hardcoding?
a=np.array([1,2,3])
print(np.repeat(a,3)) #np.repeat(a,repeat,axis=None)
print("another example",np.repeat(3,4))  #it will repeat 3 as 4 times
#How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))
#How to remove from one array those items that exist in another?
print("find which item is not common",np.setdiff1d(a,b))
#How to get the positions where elements of two arrays match?
print("where gives the indices ",np.where(a==b))
#How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print(a[index])
#How to create a 2D array containing random floats between 5 and 10?
import random 
rand_value=np.random.randint(low=5,high=10,size=(5,3))
print("random value in integer form",rand_value)
another_way=np.random.uniform(5,10,size=(5,3))
#print("floating point random generator",another_way)
#How to print only 3 decimal places in python numpy array?
print(np.set_printoptions(precision=2))
#print(another_way[:5])
#How to limit the number of items printed in output of numpy array?
np.set_printoptions(threshold=6)
a = np.arange(15)
print("like how many values you want to print",a)
#How to print the full numpy array without truncating
np.set_printoptions(threshold=np.nan)
b=np.arange(10)
print(b)
np.set_printoptions(threshold=6)
a=np.arange(15)
print("example od array with truncating",a)


# universal function 

In [ ]:
#in numpy mathematical functions such as sin,cos and exp are called "universal function"
#these functions operate element wise on array and produces array as output
a=np.array([1,2,3,4])
np.exp(a)

np.sqrt(a)

#2-dim array 
b=np.arange(12).reshape(3,4)
np.sqrt(b)

# copy and views 

In [ ]:
#when contents are physically stored in another location called copy 
import numpy as np
a=np.arange(12)
b=a      #no new object is created 
print(a)
b is a     #both are same  instance
b.shape=3,4   #let's try to cahnge the shape
b
a.shape      
b.shape         #here both are referencing to same instance of obejct

In [ ]:
#view or shallow copy
#it creates  a new array obejct same as original but   in this case  changing the shape of 'C'  does not change shape of a
a=np.arange(12)
c=a.view()
print("new view",c)
#change the shape of c     #shape does not change of original array 
c.shape=4,3
print("shape of c is",c.shape)
print("shape of original array",a.shape)

In [ ]:
#deep copy 
a=np.array( [[10,10],[2,3],[4,5]])
print("original array \n",a)

b=a.copy()
print("copy of original array",b)

#b does not share the memory of  a 
print(b is a)
b[0,0]=100
print("after modifying the array",b)
print("remains unchanged ",a)